#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Telegram command container

TELEGRAM=/drone/src/init/telegramapi
export TELEGRAM

# Caster configurations
MAINGROUP_ID="-1001372533112"
COMMIT_HASH="$(git rev-parse --verify HEAD)"
COMMIT_AUTHOR="$(git log -1 --format='%an <%ae>')"

# Push to Channel
push() {
    "${TELEGRAM}" -f "Retarded-Nightly.zip" \
    -c ${BUILDSCAPERER_ID} -t $BOT_API_KEY
}

# sendcast to group
tg_sendinfo() {
    "${TELEGRAM}" -c ${MAINGROUP_ID} -H \
    "$(
		for POST in "${@}"; do
			echo "${POST}"
		done
    )" \
    -t $BOT_API_KEY
}

# sendcast to channel
tg_channelcast() {
    "${TELEGRAM}" -c ${BUILDSCAPERER_ID} -H \
    "$(
		for POST in "${@}"; do
			echo "${POST}"
		done
    )" \
    -t $BOT_API_KEY
}

kickstart_pub() {
  if [ ! -z "$PULL_REQUEST_NUMBER" ]; then
     tg_sendinfo "I am starting build" \
     "PR: <code>${PULL_REQUEST_NUMBER}</code>" \
     "Commit Point <code>${COMMIT_POINT}</code>" \
     " " \
     "<b>Github Link: </b> https://github.com/raphielgang/telegram-userbot/commit/${COMMIT_HASH}" \
     " " \
     "<b>CI Link: </b> https://semaphoreci.com/baalajimaestro/telegram-userbot"
  else
    tg_sendinfo "I am starting build" \
    "Branch <code>${PARSE_BRANCH}</code>" \
    "Commit Point <code>${COMMIT_POINT}</code>" \
    " " \
    "<b>Github Link: </b> https://github.com/raphielgang/telegram-userbot/commit/${COMMIT_HASH}" \
    " " \
    "<b>CI Link: </b> https://semaphoreci.com/baalajimaestro/telegram-userbot"
fi
}
